version: '3.8'

networks:
  private:
    driver: bridge

services:
  mysql:
    image: mysql:8.0
    container_name: guns-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: guns
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./sql/guns.sql:/docker-entrypoint-initdb.d/guns.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    networks:
      - private

  webstack-guns:
    build: .
    container_name: webstack-guns
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/guns?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=CTT
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - private